Task1 leonov
ok-technopolis-autumn-2022/Sergei_Leonov pull request #1
Opened 2022-10-02 16:01 UTC by paikeee

2022-10-03 08:55 UTC, fromanywhere requested changes
Мне нравится, что у Вас нет классов в реализации — это подчеркивает структуру и для этого ДЗ это очень подходит

Но даже здесь стоит добавить больше выразительности, используя разнообразие тегов

2022-10-03 08:55 UTC, fromanywhere commented on index.html
> +            <label>
В чем идея label здесь?

2022-10-03 08:55 UTC, fromanywhere commented on index.html
> +                    <button>done</button>
Здесь лучше использовать другой тег

2022-10-03 08:55 UTC, fromanywhere commented on index.html
> +                <button>All</button>
Здесь лучше подумать больше о структуре и группировке

2022-10-03 08:55 UTC, fromanywhere commented on index.html
> +            <div>
Тут можно добавить больше семантики

2022-10-03 11:13 UTC, paikeee commented on index.html
> +                    <button>done</button>
Не совсем понял, где конкретно?

2022-10-03 11:19 UTC, fromanywhere commented on index.html
> +                    <button>done</button>
в 19 строке

2022-10-03 11:44 UTC, fromanywhere requested changes
Так намного лучше. После сегодняшней лекции дорабатываем в этом же PR, особенно футер

2022-10-07 14:05 UTC, fromanywhere approved these changes

2022-10-07 14:06 UTC, fromanywhere approved these changes

2022-10-07 14:06 UTC, fromanywhere commented on index.html
> +                <input type="radio" aria-label="all todos" checked>
name нужно проставить

2022-10-29 15:06 UTC, merged